SoftwareAG/c8y-releasenotes

- content/release-10-14-0/announcements-10-14-0.md
Copied over from the Analytics Builder release notes at https://docbuilder1.eur.ad.sag/jenkins/job/pab/job/trunk-webhelp_en/lastSuccessfulBuild/artifact/out/webhelp/index.html#page/apamaanalyticsbuilder-webhelp%2Fco-AnaBui_whats_new_1014.html
> PAB-3105: frgment => fragment

- content/release-10-14-0/streaming-analytics-10-14-0-bundle/10_14_0.md
Copied over release note from the Analytics Builder DITA doc.
> PAB-3114: Add a release note regarding the use of measurement value

- content/release-10-10-0/oee-10-10-0-bundle/10_10_0_3.md
Recreated pull request for OEE 1010.0.3 Fix.
> Release notes for OEE 1010.0.3.

- content/release-10-13-0/edge-10-13-0-bundle/10_13_0.md
@rssag and @BeateRixen - Would it be possible to publish this by today?
> Edge RN. Added an alias for Edge RN.

- content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0.md
Copied over several release notes from the Analytics Builder DITA doc.
> PAB-3206: release notes for samples and more

- content/release-10-10-0/streaming-analytics-10-10-0-bundle/10_10_0_12.md
This needs to go live the next time the release notes are updated on the public website. Therefore, I need to create one more PR for merging a cherry-pick into main.
> PAB-3285: Added 10.10.0.12 fix release note

- content/release-10-15-0/announcements-10-15-0.md
Copied over several C8Y-related entries from the PAM 10.15 release notes into the "Important announcements".
> PAB-3241: Include important information from the PAM 10.15 release notes also in the C8Y 10.15 release notes

- content/release-10-14-0/announcements-10-14-0.md
change oai-secure annoucements
> MTM-46238 - Announcement for the breaking change

- content/release-10-11-0/streaming-analytics-10-11-0-bundle/10_11_0_7.md
- content/release-10-13-0/streaming-analytics-10-13-0-bundle/10_13_0_5.md
- content/release-10-14-0/streaming-analytics-10-14-0-bundle/10_14_0_4.md
Once this has been approved and merged into develop, this can also be merged into the main branch to go live soon.
> Release notes for PAQ fixes to 10.11, 10.13 and 10.14

- content/release-10-15-0/datahub-10-15-0-bundle/10_15_0.md
- content/release-10-15-0/datahub-10-15-0-bundle/index.html
- content/release-10-15-0/datahub-10-15-0.md
Hi Beate,
can you pls merge to 10.15?
Thanks
Christoph
> [NO-JIRA] Version without Dremio 22

- content/release-10-16-0/digital-twin-manager-10-16-0-bundle/10-16-0-0.md
- content/release-10-16-0/digital-twin-manager-10-16-0-bundle/index.html
- content/release-10-16-0/digital-twin-manager-10-16-0.md
@lra-sag, @rssag, @MWindel, Please review the Release notes for 10.16 version of DTM
> Release Notes for DTM 10.16

- content/release-10-16-0/digital-twin-manager-10-16-0-bundle/10-16-0-0.md
@BeateRixen, @lra-sag please review and approve the minor change which is added as part of the release notes
> Updated the DTM 10.16 release notes

- content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0_4.md
@skom-sag , I've added 10.15.0.3 as the Apama version at the top. Is this corrrect?
> Release note for PAQ 10.15.0.4 fix

- content/release-10-17-0/streaming-analytics-10-17-0-bundle/10_17_0.md
@skom-sag , is this wording ok or do you have something better? 
Do you already have input for the new multi-tenant variant of the Apama-ctrl microservice (see my TODO comment in the release note) or should I wait with this?
> Release note for new multi-tenant sample (PAB-3529)

- content/release-10-16-0/digital-twin-manager-10-16-0-bundle/10-16-0-0.md
Updated the release notes content for DTM application
> Dtm update

- content/release-10-13-0/announcements-10-13-0.md
- content/release-10-13-0/machine-learning-10-13-0-bundle/10_13_0.md
added announcement for 10.13 fix release
> added announcement for 10.13 fix release

- content/release-10-17-0/streaming-analytics-10-17-0-bundle/10_17_0.md
> PAB-3528: Copied over 10.17 release note from Analytics Builder (DITA) doc

- content/release-10-16-0/announcements-10-16-0.md
- content/release-10-17-0/announcements-10-17-0.md
causing braking change in security config
Related to https://github.com/SoftwareAG/c8y-docs/pull/792
> MTM-49761 Announcement of Spring Boot update in Microservice SDK

- content/release-10-17-0/digital-twin-manager-10-17-0-bundle/10-17-0-0.md
- content/release-10-17-0/digital-twin-manager-10-17-0-bundle/index.html
- content/release-10-17-0/digital-twin-manager-10-17-0.md
Added the release notes for 10.17 version of DTM. Please review.
> Release notes for DTM 10.17 version

- content/release-10-17-0/streaming-analytics-10-17-0-bundle/10_17_0.md
> PAB-3701: Copied over release note from 10.17 Analytics Buider release note

- content/release-10-16-0/digital-twin-manager-10-16-0-bundle/10-16-0-1.md
- content/release-10-16-0/digital-twin-manager-10-16-0-bundle/index.html
- content/release-10-16-0/digital-twin-manager-10-16-0.md
Added the release notes for 10.16.0.1 version of DTM
> Added the release notes for 10.16.0.1 version of DTM

- content/release-10-17-0/announcements-10-17-0.md
Added the deprecation information of DTM
> Added the deprecation information of DTM

- content/release-10-17-0/announcements-10-17-0.md
- content/release-10-17-0/datahub-10-17-0-bundle/10_17_0.md
- content/release-10-17-0/datahub-10-17-0-bundle/index.html
- content/release-10-17-0/datahub-10-17-0.md
> CDH-3581: Initial version of release notes

- content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0_7.md
This fix is already in status Released-Controlled. So this can go live as soon as one of the developers has approved this.
> PAQ release note for 10.15.0.7 (PAB-3982)

- content/release-10-18-0/whatsnew-10-18-0.md
> MTM-52999: announce authentication with access tokens from authorization

- content/release-10-18-0/announcements-10-18-0.md
> PAB-3674: removed roles

- content/release-10-17-0/announcements-10-17-0.md
- content/release-10-18-0/announcements-10-18-0.md
> [MTM-52969]: Announcement about a breaking change related to 'totalPages' statistic removal

- content/release-10-17-0/digital-twin-manager-10-17-0-bundle/10-17-0-0.md
> Updated the content for DTM

- content/release-10-18-0/digital-twin-manager-10-18-0-bundle/10-18-0-0.md
Changed all instances from **Asset tree** page to **Asset tree** tab.
> Asset tree page to tab

- content/release-10-18-0/announcements-10-18-0.md
Need to ask the developer via iTrac to verify this.
> PAB-4042: Update the release note about Zementis sample

- content/release-10-18-0/announcements-10-18-0.md
- content/release-10-18-0/streaming-analytics-10-18-0-bundle/10_18_0.md
Need to ask a developer via iTrac to review this. Not sure if more needs to be copied over.
> PAB-4048: Copy over C8Y-specific info from the Apama 10.15.3 release notes

- content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0_8.md
This fix is already in status Released-Controlled. So this can go live immediately.
> PAB-4006: Release note for PAQ 10.15.0.8 fix

- content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_4.md
This is the cherry-pick into the main branch so that this can go live now.
(cherry picked from commit 15eb52d8257bef88bfbb925533732f44d49fa5f4)
> Release note for PAQ 10.16.0.4 fix

- content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_1.md
- content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_2.md
- content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_3.md
- content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_4.md
Use the word "Fix" as requested by Rob and Kev (that is, use same fix title as in Empower).
> PAQ: Small change in "fix" wording

- content/release-10-17-0/announcements-10-17-0.md
- content/release-10-18-0/announcements-10-18-0.md
- content/release-2024-0/announcements-2024-0.md
One in 1017 about the deprecation of the data grid logic, the same in 1018, and one in 1019 about the removal of the logic.
> [DM-1294]: Added 3 announcements for device grid changes.

- content/release-10-14-0/streaming-analytics-10-14-0-bundle/10_14_0_6.md
> Fix release note for PAQ 10.14.0.6 (PAB-3714)

- content/release-10-14-0/streaming-analytics-10-14-0-bundle/10_14_0_6.md
(cherry picked from commit 85e51c87c172810f1da09592716123390f780dbd)
This can go live now. @BeateRixen , please merge and publish.
> Fix release note for PAQ 10.14.0.6 (PAB-3714) to go live now

- content/release-10-18-0/datahub-10-18-0-bundle/10_18_0.md
Hi,
can you pls review and merge to develop and 10.18?
Thanks!
> [NO-JIRA] Notes on performance characteristics

- content/release-10-18+/streaming-analytics-10-18+-bundle/10.18+_0.md
Also sent a mail to Rob, asking him to look into this release note. He responded and I added his feedback to this PR.
> Release note for new Add Devices option (PAB-4182)

- content/release-10-17-0/applications-10-17-0-bundle/applications-10-17-0-346.md
- content/release-10-17-0/devices-10-17-0-bundle/devices-10-17-0-346.md
- content/release-10-17-0/platform-10-17-0-bundle/platform-10-17-0-346.md
The name of the branch is nonsense. Should be 10.17.0.346
> added release notes for 10.17.0.346

- content/release-10-18-0/announcements-10-18-0.md
> Gainsight releasenotes

- content/release-10-17-0/digital-twin-manager-10-17-0-bundle/10-17-0-0-669.md
- content/release-10-17-0/digital-twin-manager-10-17-0-bundle/10-17-0-0-696.md
Updated the DTM file name with respect to build version and moved the contents accordingly for better readability
> Updated the file name with respect to build version

- content/release-10-17-0/streaming-analytics-10-17-0-bundle/10_18_0_9.md
- content/release-10-18-0/streaming-analytics-10-18-0-bundle/10_18_0_9.md
> Release note for 10.18.0.9 

- content/release-10-17-0/streaming-analytics-10-17-0-bundle/10_18_0_10.md
- content/release-10-18-0/streaming-analytics-10-18-0-bundle/10_18_0_10.md
Added to both release trains, 10.18 and 10.17.
@ddfourni1 , please let us know when this can go live.
> PAQ release note for 10.18.0.10 (PAB-4526)
