SoftwareAG/c8y-releasenotes

content/release-10-14-0/streaming-analytics-10-14-0-bundle/10_14_0.md

Added information on the Apama correlator version, copied over info from the Analytics Builder release notes, and also some C8Y-specific info from the PAM 10.11.3 release notes.

Streaming Analytics 10.14 release notes

---

content/release-10-14-0/streaming-analytics-10-14-0-bundle/10_14_0.md

Copied over the release note for the new Time input port from the Analytics Builder doc at https://docbuilder1.eur.ad.sag/jenkins/job/pab/job/trunk-webhelp_en/lastSuccessfulBuild/artifact/out/webhelp/index.html#page/apamaanalyticsbuilder-webhelp%2Fco-AnaBui_whats_new_1014.html
and also fixed the previous paragraph on the new samples.
Keep in mind that the links to the 10.14 Analytics Builder doc do not yet work as this has not yet been published.

PAB-3089: New Time input port

---

content/release-10-14-0/announcements-10-14-0.md

Copied over from PAM release notes that user must have ROLE_EMAIL_CREATE permission for sending email requests from Apama to Cumulocity IoT.

PAM-33546 - Release note for ROLE_EMAIL_CREATE

---

content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0.md

Copied over 10.15 release note from the Analytics Builder doc for support of globalTitle.

PAB-3219: Release note for Analytics Builder support of globalTitle

---

content/release-10-6-6/streaming-analytics-10-6-6-bundle/10_6_6_30.md

Added release note for 10.6.6.30 fix. But still need to find out the correct version numbers for Apama.

PAB-3254: Release note for 10.6.6.30 fix

---

content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0.md

Copied over from https://docbuilder1.eur.ad.sag/jenkins/job/pab/job/trunk-webhelp_en/lastSuccessfulBuild/artifact/out/webhelp/index.html#page/apamaanalyticsbuilder-webhelp%2Fco-AnaBui_whats_new_1015.html that it's now possible to search for Analytics Builder samples with specific words in their names and to filter them by tags.

PAB-3305: Search and filter Analytics Builder samples

---

content/release-10-13-0/streaming-analytics-10-13-0-bundle/10_13_0_3.md
content/release-10-13-0/streaming-analytics-10-13-0-bundle/10_13_0_4.md

This is for both PAB-3283 and PAB-3315, and can go live the next time the public C8Y release notes are updated.
Received developer confirmation on the iTrac that the release notes look good.

Release notes for the PAQ 10.13.0.3 and 10.13.0.4 fixes

---

content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0.md

This is part of the changes for the automatic deployment of the DITA doc onto the doc website. The folder structure on the doc website will change for 10.15 when all docs for the October release will go live. Therefore I adapted the links to the Apama and Analytics Builder doc in the 10.15 release notes. Note that the links won't change for the webhelps of the previous versions - they remain as they are.
Unfortunately, we cannot yet check if the changed links do really work. This has to wait until the middle of October 2022.

PAB-3323: Update the links to the 10.15 PAM and PAB webhelps

---

content/release-10-14-0/streaming-analytics-10-14-0-bundle/10_14_0_3.md

This can go live the next time the 10.14 release notes are updated on the public website.
Therefore, this also needs to be cherry-picked into "main" via one more PR.

PAQ 10.14.0.3 fix release note

---

content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0.md

Added PAM correlator version and copied over 10.16.0 release notes from Analytics Builder doc. Need to make sure that the new URLs to the PAM and PAB doc will work (to be done later when these URLs are finally available on the doc website).

Add release notes for Streaming Analytics 10.16

---

content/release-10-17-0/streaming-analytics-10-17-0-bundle/10_17_0.md

Copied over release note on tooltip improvement from the Analytics Builder doc.

PAB-3560: Improved tooltip input and output ports

---

content/release-10-18-0/announcements-10-18-0.md

Turns out our fix for PAB-3674 was breaking, so we've pulled the change for now, therefore it shouldn't be in the doc.

Revert "PAB-3674: removed roles"

---

content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0_6.md

This will replace https://github.com/SoftwareAG/c8y-releasenotes/pull/177.
@skom-sag  and @ddfourni1 , I still need to know which text to use for PAB-3605 (see also my comment in the release note and Sharon's mail thread).

PAQ release notes for 10.15.0.6 (PAB-3699)

---

content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_2.md
content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_3.md

The release notes for 10.16.0.2 and 10.16.0.3 can both go live when https://itrac.eur.ad.sag/browse/PAB-3949 moves to RELEASED-CONTROLLED.

Release notes for PAQ 10.16.0.2 and 10.16.0.3 fixes

---

content/release-10-17-0/announcements-10-17-0.md
content/release-10-18-0/announcements-10-18-0.md

Hi @BeateRixen , I need your advice. I have been asked to add exactly the same release note to 10.18 (PAB-4004). Is this something that we normally do? Or is it sufficient to mention this only once, that is, in 10.17 where I've just updated the release note (done with this PR)?

PAB-4007: Update existing release note about Machine Learning deprecation 

---

content/release-10-18-0/streaming-analytics-10-18-0-bundle/10_18_0.md

In addition to the new release note, I've also added links to the block reference which is now part of the Streaming Analytics guide.

PAB-4009: 10.18 release note for Alarm Output block

---

content/release-2024-0/streaming-analytics-2024-0-bundle/2024_0.md
content/release-2024-0/streaming-analytics-2024-0-bundle/index.html
content/release-2024-0/streaming-analytics-2024-0.md

Added the bundle for Streaming Analytics release notes to collect the PAQ changes. Did this in the "old" way for now. This can still be changed later when it has finally been decided how the release notes for CD are to look like.
Note that the link to the Streaming Analytics guide has 10.19 in the URL for now. This needs to be changed later - globally - when the final URL for the 10.18+ (CD) user doc is known.

PAQ: New EPL sample named "Receive update notifications" (PAB-1663)

---

content/release-10-17-0/streaming-analytics-10-17-0-bundle/10_18_0_3.md
content/release-10-18-0/streaming-analytics-10-18-0-bundle/10_18_0_3.md

Also needs to be copied to /release-10-17-0/streaming-analytics-10-17-0-bundle when the 10.18 release note has been approved by the dev team.

Release notes for the 10.18.0.3 fix (PAB-4160)

---

content/release-10-17-0/announcements-10-17-0.md
content/release-10-18-0/announcements-10-18-0.md

This also needs to be copied over into the 10.18 release notes.
And the 10.17 release note needs to be cherry-picked so that it can go live.

PAQ: Breaking change for acknowledged alarms

---

content/release-10-17-0/announcements-10-17-0.md
content/release-10-18-0/announcements-10-18-0.md

Hi,
can you pls review and merge to develop, 10.18, and 10.17? For the latter merge the changes to the 10.18 announcements file can be ignored.
Thanks!

[NO-JIRA] Deprecation of HDFS support in DataHub

---

content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_5.md

(cherry picked from commit fc966ff870dfc0fc55216e03240846e2a1122feb)
To go live when 10.16.0.5 reaches the last column at
https://pages.github.softwareag.com/IOTA/c8y-iot-build-pipeline/10.16.0.x.html
(maybe by the end of this week or later)

Publish fix release note for 10.16.0.5 (PAB-4161)

---

content/release-10-15-0/streaming-analytics-10-15-0-bundle/10_15_0_9.md

(cherry picked from commit 24bf123ffb484aa02e02e0a5a4a2043d6a1166d4)
To go live when 10.15.0.9 reaches the last column at
https://pages.github.softwareag.com/IOTA/c8y-iot-build-pipeline/10.15.0.x.html
(maybe by the end of this week or later)

Publish fix release note for 10.15.0.9 (PAB-4162)

---

content/release-10-18-0/announcements-10-18-0.md

Removed duplicate (and partly wrong) information on the German doc. Also removed info on English doc - someone has rearranged the 10.17 release note and moved the info on the German and English doc to a different section. So we need not repeat this now in 10.18. We need to make sure that the 10.17 and 10.18 release notes for Streaming Analytics are exactly the same (except for updated links).

PAQ 10.18: Remove info on English and German Analytics Builder doc

---

content/release-10-17-0/streaming-analytics-10-17-0-bundle/10_18_0_4.md

The PAQ 10.18.0.4 release note also needs to be added to the 10.17 release train.

Copy over PAQ 10.18.0.4 release note into 10.17

---

content/release-10-18+/announcements-10-18+.md
content/release-10-18-0/announcements-10-18-0.md

As the issue with npm has been resolved we can remove this announcement again.

[no-issue] remove npm workaround announcement

---

content/release-10-18+/streaming-analytics-10-18+-bundle/10.18+_0.md

Shruti, please make sure that this release note is what you want. I checked the C8Y doc for groups and tried to use the corresponding wording. Looks like they talk about "subassets" now and no longer "child devices" ... ???

PAB-4299: Missing device in a group is now ignored

---

content/release-10-18-0/streaming-analytics-10-18-0.md

Added a link to the CD change log at the top of the 10.18 Streaming Analytics release notes as requested by Rob.

Link to CD change log for Streaming Analytics.

---

content/release-10-16-0/streaming-analytics-10-16-0-bundle/10_16_0_6.md

@ddfourni1 , @skom-sag , this is a first draft. Not sure if all is correct.
PAB-4361:
There's no readme text on the parent defect. But there's a link to the c8y-releasenotes on PAB-4361 itself, for a RN that has been added for 10.17. I've also added that text now for 10.16.0.6. Is this correct?
PAB-4373: 
There's no readme text on the parent defect. But PAB-4373 itself has a readme text, and I've added this. Ok?
PAB-4395:
Took the readme text from the parent.

Release note for PAQ 10.16.0.6
